vscode:
  extensions:
    - anseki.vscode-color@0.4.5:6L3EhKJFHuizA7wqZz6/+g==
    - HansUXdev.bootstrap5-snippets@1.2.4:a0VDfZWXIZ8kLhp9GNm4DA==
    - ritwickdey.LiveServer@5.6.1:5Mhl1RgVVDcIym163x8r+w==
    - csstools.postcss@1.0.8:2se5vOc1Tk93L+FlbGsY9g==
    - ecmel.vscode-html-css@0.2.3:hh8R73s3n0g/eQ8EL9PatQ==
    - pranaygp.vscode-css-peek@4.0.2:sjXY3M4jzrmbd2itCL2o1Q==
    - Zignd.html-css-class-completion@1.19.0:Soyzg8syqQX3vm86CKnPtg==